name: game_map_master_flutter_app
description: AndroidApp GamemapMaster
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # Gestion d'état
  provider: ^6.0.5
  # HTTP et WebSocket
  http: ^1.3.0
  web_socket_channel: ^2.3.0
  # Stockage local
  shared_preferences: ^2.1.0
  # Scanner QR code
  mobile_scanner: ^3.5.2
  qr_flutter: ^4.1.0
  # Navigation
  go_router: ^7.0.0
  # UI
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1
  # Authentification
  jwt_decoder: ^2.0.1
  # Localisation
  geolocator: ^10.1.0
  # google_maps_flutter: ^2.2.6 # Remplacé par flutter_map
  flutter_map: ^6.1.0 # Ajout de flutter_map pour OpenStreetMap
  latlong2: ^0.9.0 # Dépendance pour flutter_map
  # Autres
  intl: 0.20.2
  uuid: 4.5.1
  logger: ^2.0.1
  flutter_datetime_picker_plus: ^2.1.0
  stomp_dart_client: ^0.4.4
  flutter_local_notifications: ^19.0.0
  get_it: ^7.6.0
  qr_code_scanner_plus: ^2.0.10+1
  path_provider: ^2.0.15
  share_plus: ^7.0.2
  pdf: ^3.11.3
  printing: ^5.14.2
  archive: ^3.3.8
  # Pour la capture d'écran (widget en image)
  screenshot: ^3.0.0 # Ajout pour la capture d'image de fond
  flutter_colorpicker: ^1.0.3
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/NotoSansSymbols2-Regular.ttf

dependency_overrides:
  geolocator_android: ^4.4.3
flutter_intl:
  enabled: true